//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteApp.MySpace.Assets.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiteApp.MySpace.Assets.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more files.
        /// </summary>
        public static string AddMoreFilesButtonText {
            get {
                return ResourceManager.GetString("AddMoreFilesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few words about what I planned to create. First of all, it should be a simple, customizable control. The only limitation - I didn&apos;t want to hard code its geometry, a shape of animated element. This element is defined in the Generic.xaml file, but can be redefined as a part of a user&apos;s Style.
        ///
        ///If you look at the Generic.xaml, you will see only one animation element AnimationElementTemplate defined as a DataTemplate. The problem was to manifold it. I was surprised to know that deep object cloning is a cha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ALot {
            get {
                return ResourceManager.GetString("ALot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space of Rui.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel upload.
        /// </summary>
        public static string CancelUploadMessageHeader {
            get {
                return ResourceManager.GetString("CancelUploadMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose files.
        /// </summary>
        public static string ChooseFilesButtonText {
            get {
                return ResourceManager.GetString("ChooseFilesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmationWindowTitle {
            get {
                return ResourceManager.GetString("ConfirmationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some photos are being uploaded. This will stop all the uploads. Are you sure you want to continue?.
        /// </summary>
        public static string ConfirmCancelUploadPhotoMessage {
            get {
                return ResourceManager.GetString("ConfirmCancelUploadPhotoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected items will be deleted permanently. Are you sure you want to continue?.
        /// </summary>
        public static string ConfirmDeleteItemsMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create album.
        /// </summary>
        public static string CreateAlbumButtonText {
            get {
                return ResourceManager.GetString("CreateAlbumButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create album.
        /// </summary>
        public static string CreateAlbumWindowTitle {
            get {
                return ResourceManager.GetString("CreateAlbumWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButtonText {
            get {
                return ResourceManager.GetString("CreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete photos.
        /// </summary>
        public static string DeletePhotosMessageHeader {
            get {
                return ResourceManager.GetString("DeletePhotosMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This comment is being deleted....
        /// </summary>
        public static string DeletingCommentMessage {
            get {
                return ResourceManager.GetString("DeletingCommentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit album.
        /// </summary>
        public static string EditAlbumWindowTitle {
            get {
                return ResourceManager.GetString("EditAlbumWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your album a name.
        /// </summary>
        public static string GiveAlbumName {
            get {
                return ResourceManager.GetString("GiveAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string HideButtonText {
            get {
                return ResourceManager.GetString("HideButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No album is found.
        /// </summary>
        public static string NoAlbumFoundMessage {
            get {
                return ResourceManager.GetString("NoAlbumFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButtonText {
            get {
                return ResourceManager.GetString("NoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comment is found.
        /// </summary>
        public static string NoCommentFoundMessage {
            get {
                return ResourceManager.GetString("NoCommentFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo is found.
        /// </summary>
        public static string NoPhotoFoundMessage {
            get {
                return ResourceManager.GetString("NoPhotoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered yet?.
        /// </summary>
        public static string NotRegisteredYetMessage {
            get {
                return ResourceManager.GetString("NotRegisteredYetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string OperationFailedMessageHeader {
            get {
                return ResourceManager.GetString("OperationFailedMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation needs you to sign in first..
        /// </summary>
        public static string OperationNeedsSignInMessage {
            get {
                return ResourceManager.GetString("OperationNeedsSignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string PhotosPageTitle {
            get {
                return ResourceManager.GetString("PhotosPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostButtonText {
            get {
                return ResourceManager.GetString("PostButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing... Please wait.
        /// </summary>
        public static string ProcessingMessage {
            get {
                return ResourceManager.GetString("ProcessingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in failed.
        /// </summary>
        public static string SignInFailedMessageHeader {
            get {
                return ResourceManager.GetString("SignInFailedMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing you int....
        /// </summary>
        public static string SigningInMessage {
            get {
                return ResourceManager.GetString("SigningInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string SignInLinkText {
            get {
                return ResourceManager.GetString("SignInLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in is required.
        /// </summary>
        public static string SignInRequiredMessageHeader {
            get {
                return ResourceManager.GetString("SignInRequiredMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInWindowTitle {
            get {
                return ResourceManager.GetString("SignInWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOutButtonText {
            get {
                return ResourceManager.GetString("SignOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now.
        /// </summary>
        public static string SignUpNowButtonText {
            get {
                return ResourceManager.GetString("SignUpNowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpWindowTitle {
            get {
                return ResourceManager.GetString("SignUpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take me back to.
        /// </summary>
        public static string TakeMeBackToPhrase {
            get {
                return ResourceManager.GetString("TakeMeBackToPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To post any comment, please.
        /// </summary>
        public static string ToPostCommentPleasePhrase {
            get {
                return ResourceManager.GetString("ToPostCommentPleasePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadButtonText {
            get {
                return ResourceManager.GetString("UploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string UploadingPhrase {
            get {
                return ResourceManager.GetString("UploadingPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose more than one file at a time. Upload will start immediately after choosing files..
        /// </summary>
        public static string UploadPhotoInstruction {
            get {
                return ResourceManager.GetString("UploadPhotoInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        public static string UploadPhotoWindowTitle {
            get {
                return ResourceManager.GetString("UploadPhotoWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to.
        /// </summary>
        public static string UploadToPhrase {
            get {
                return ResourceManager.GetString("UploadToPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewButtonText {
            get {
                return ResourceManager.GetString("ViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ViewDetailsLinkText {
            get {
                return ResourceManager.GetString("ViewDetailsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButtonText {
            get {
                return ResourceManager.GetString("YesButtonText", resourceCulture);
            }
        }
    }
}
