//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace LiteApp.MySpace.Services.Photo {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResultOfAlbumYX32z0hB", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.Services")]
    public partial class PagedResultOfAlbumYX32z0hB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.Album> EntitiesField;
        
        private int TotalItemCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.Album> Entities {
            get {
                return this.EntitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitiesField, value) != true)) {
                    this.EntitiesField = value;
                    this.RaisePropertyChanged("Entities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItemCount {
            get {
                return this.TotalItemCountField;
            }
            set {
                if ((this.TotalItemCountField.Equals(value) != true)) {
                    this.TotalItemCountField = value;
                    this.RaisePropertyChanged("TotalItemCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Album", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.Entities")]
    public partial class Album : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<string> CoverURIsField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedOnField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private string NameField;
        
        private int PhotoCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> CoverURIs {
            get {
                return this.CoverURIsField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverURIsField, value) != true)) {
                    this.CoverURIsField = value;
                    this.RaisePropertyChanged("CoverURIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhotoCount {
            get {
                return this.PhotoCountField;
            }
            set {
                if ((this.PhotoCountField.Equals(value) != true)) {
                    this.PhotoCountField = value;
                    this.RaisePropertyChanged("PhotoCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.FaultHandling")]
    public partial class ServerFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LiteApp.MySpace.Services.Photo.ServerFaultCode FaultCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LiteApp.MySpace.Services.Photo.ServerFaultCode FaultCode {
            get {
                return this.FaultCodeField;
            }
            set {
                if ((this.FaultCodeField.Equals(value) != true)) {
                    this.FaultCodeField = value;
                    this.RaisePropertyChanged("FaultCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerFaultCode", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.FaultHandling")]
    public enum ServerFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Generic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAuthroized = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResultOfPhotoYX32z0hB", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.Services")]
    public partial class PagedResultOfPhotoYX32z0hB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.Photo> EntitiesField;
        
        private int TotalItemCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.Photo> Entities {
            get {
                return this.EntitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitiesField, value) != true)) {
                    this.EntitiesField = value;
                    this.RaisePropertyChanged("Entities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItemCount {
            get {
                return this.TotalItemCountField;
            }
            set {
                if ((this.TotalItemCountField.Equals(value) != true)) {
                    this.TotalItemCountField = value;
                    this.RaisePropertyChanged("TotalItemCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photo", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.Entities")]
    public partial class Photo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AlbumIdField;
        
        private int CommentCountField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedOnField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private string PhotoURIField;
        
        private string ThumbURIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlbumId {
            get {
                return this.AlbumIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumIdField, value) != true)) {
                    this.AlbumIdField = value;
                    this.RaisePropertyChanged("AlbumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentCount {
            get {
                return this.CommentCountField;
            }
            set {
                if ((this.CommentCountField.Equals(value) != true)) {
                    this.CommentCountField = value;
                    this.RaisePropertyChanged("CommentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoURI {
            get {
                return this.PhotoURIField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoURIField, value) != true)) {
                    this.PhotoURIField = value;
                    this.RaisePropertyChanged("PhotoURI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbURI {
            get {
                return this.ThumbURIField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbURIField, value) != true)) {
                    this.ThumbURIField = value;
                    this.RaisePropertyChanged("ThumbURI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletePhotoParameters", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.Services")]
    public partial class DeletePhotoParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FileNameField;
        
        private string PhotoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoId {
            get {
                return this.PhotoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoIdField, value) != true)) {
                    this.PhotoIdField = value;
                    this.RaisePropertyChanged("PhotoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoComment", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.Entities")]
    public partial class PhotoComment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AlbumIdField;
        
        private string ContentsField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedOnField;
        
        private string IdField;
        
        private string PhotoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlbumId {
            get {
                return this.AlbumIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumIdField, value) != true)) {
                    this.AlbumIdField = value;
                    this.RaisePropertyChanged("AlbumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contents {
            get {
                return this.ContentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentsField, value) != true)) {
                    this.ContentsField = value;
                    this.RaisePropertyChanged("Contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoId {
            get {
                return this.PhotoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoIdField, value) != true)) {
                    this.PhotoIdField = value;
                    this.RaisePropertyChanged("PhotoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="Services.Photo.PhotoService")]
    public interface PhotoService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/GetPagedAlbums", ReplyAction="urn:PhotoService/GetPagedAlbumsResponse")]
        System.IAsyncResult BeginGetPagedAlbums(int pageIndex, int pageSize, System.AsyncCallback callback, object asyncState);
        
        LiteApp.MySpace.Services.Photo.PagedResultOfAlbumYX32z0hB EndGetPagedAlbums(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/SaveAlbum", ReplyAction="urn:PhotoService/SaveAlbumResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LiteApp.MySpace.Services.Photo.ServerFault), Action="urn:PhotoService/SaveAlbumServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.FaultHandling")]
        System.IAsyncResult BeginSaveAlbum(LiteApp.MySpace.Services.Photo.Album album, System.AsyncCallback callback, object asyncState);
        
        void EndSaveAlbum(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/DeleteAlbum", ReplyAction="urn:PhotoService/DeleteAlbumResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LiteApp.MySpace.Services.Photo.ServerFault), Action="urn:PhotoService/DeleteAlbumServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.FaultHandling")]
        System.IAsyncResult BeginDeleteAlbum(string albumId, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteAlbum(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/GetPagedPhotos", ReplyAction="urn:PhotoService/GetPagedPhotosResponse")]
        System.IAsyncResult BeginGetPagedPhotos(int pageIndex, int pageSize, string albumId, System.AsyncCallback callback, object asyncState);
        
        LiteApp.MySpace.Services.Photo.PagedResultOfPhotoYX32z0hB EndGetPagedPhotos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/DeletePhotos", ReplyAction="urn:PhotoService/DeletePhotosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LiteApp.MySpace.Services.Photo.ServerFault), Action="urn:PhotoService/DeletePhotosServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.FaultHandling")]
        System.IAsyncResult BeginDeletePhotos(System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.DeletePhotoParameters> photos, string albumId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndDeletePhotos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/UpdateDescription", ReplyAction="urn:PhotoService/UpdateDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LiteApp.MySpace.Services.Photo.ServerFault), Action="urn:PhotoService/UpdateDescriptionServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.FaultHandling")]
        System.IAsyncResult BeginUpdateDescription(string description, string photoId, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateDescription(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/GetComments", ReplyAction="urn:PhotoService/GetCommentsResponse")]
        System.IAsyncResult BeginGetComments(string photoId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.PhotoComment> EndGetComments(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/SaveComment", ReplyAction="urn:PhotoService/SaveCommentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LiteApp.MySpace.Services.Photo.ServerFault), Action="urn:PhotoService/SaveCommentServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.FaultHandling")]
        System.IAsyncResult BeginSaveComment(LiteApp.MySpace.Services.Photo.PhotoComment comment, System.AsyncCallback callback, object asyncState);
        
        LiteApp.MySpace.Services.Photo.PhotoComment EndSaveComment(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:PhotoService/DeleteComment", ReplyAction="urn:PhotoService/DeleteCommentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LiteApp.MySpace.Services.Photo.ServerFault), Action="urn:PhotoService/DeleteCommentServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/LiteApp.MySpace.Web.FaultHandling")]
        System.IAsyncResult BeginDeleteComment(string commentId, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteComment(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PhotoServiceChannel : LiteApp.MySpace.Services.Photo.PhotoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPagedAlbumsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPagedAlbumsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LiteApp.MySpace.Services.Photo.PagedResultOfAlbumYX32z0hB Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LiteApp.MySpace.Services.Photo.PagedResultOfAlbumYX32z0hB)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPagedPhotosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPagedPhotosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LiteApp.MySpace.Services.Photo.PagedResultOfPhotoYX32z0hB Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LiteApp.MySpace.Services.Photo.PagedResultOfPhotoYX32z0hB)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeletePhotosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeletePhotosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.PhotoComment> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.PhotoComment>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LiteApp.MySpace.Services.Photo.PhotoComment Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LiteApp.MySpace.Services.Photo.PhotoComment)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhotoServiceClient : System.ServiceModel.ClientBase<LiteApp.MySpace.Services.Photo.PhotoService>, LiteApp.MySpace.Services.Photo.PhotoService {
        
        private BeginOperationDelegate onBeginGetPagedAlbumsDelegate;
        
        private EndOperationDelegate onEndGetPagedAlbumsDelegate;
        
        private System.Threading.SendOrPostCallback onGetPagedAlbumsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveAlbumDelegate;
        
        private EndOperationDelegate onEndSaveAlbumDelegate;
        
        private System.Threading.SendOrPostCallback onSaveAlbumCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteAlbumDelegate;
        
        private EndOperationDelegate onEndDeleteAlbumDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteAlbumCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPagedPhotosDelegate;
        
        private EndOperationDelegate onEndGetPagedPhotosDelegate;
        
        private System.Threading.SendOrPostCallback onGetPagedPhotosCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeletePhotosDelegate;
        
        private EndOperationDelegate onEndDeletePhotosDelegate;
        
        private System.Threading.SendOrPostCallback onDeletePhotosCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDescriptionDelegate;
        
        private EndOperationDelegate onEndUpdateDescriptionDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateDescriptionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCommentsDelegate;
        
        private EndOperationDelegate onEndGetCommentsDelegate;
        
        private System.Threading.SendOrPostCallback onGetCommentsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveCommentDelegate;
        
        private EndOperationDelegate onEndSaveCommentDelegate;
        
        private System.Threading.SendOrPostCallback onSaveCommentCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteCommentDelegate;
        
        private EndOperationDelegate onEndDeleteCommentDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCommentCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PhotoServiceClient() {
        }
        
        public PhotoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhotoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetPagedAlbumsCompletedEventArgs> GetPagedAlbumsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveAlbumCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteAlbumCompleted;
        
        public event System.EventHandler<GetPagedPhotosCompletedEventArgs> GetPagedPhotosCompleted;
        
        public event System.EventHandler<DeletePhotosCompletedEventArgs> DeletePhotosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateDescriptionCompleted;
        
        public event System.EventHandler<GetCommentsCompletedEventArgs> GetCommentsCompleted;
        
        public event System.EventHandler<SaveCommentCompletedEventArgs> SaveCommentCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCommentCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginGetPagedAlbums(int pageIndex, int pageSize, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPagedAlbums(pageIndex, pageSize, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiteApp.MySpace.Services.Photo.PagedResultOfAlbumYX32z0hB LiteApp.MySpace.Services.Photo.PhotoService.EndGetPagedAlbums(System.IAsyncResult result) {
            return base.Channel.EndGetPagedAlbums(result);
        }
        
        private System.IAsyncResult OnBeginGetPagedAlbums(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pageIndex = ((int)(inValues[0]));
            int pageSize = ((int)(inValues[1]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginGetPagedAlbums(pageIndex, pageSize, callback, asyncState);
        }
        
        private object[] OnEndGetPagedAlbums(System.IAsyncResult result) {
            LiteApp.MySpace.Services.Photo.PagedResultOfAlbumYX32z0hB retVal = ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndGetPagedAlbums(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPagedAlbumsCompleted(object state) {
            if ((this.GetPagedAlbumsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPagedAlbumsCompleted(this, new GetPagedAlbumsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPagedAlbumsAsync(int pageIndex, int pageSize) {
            this.GetPagedAlbumsAsync(pageIndex, pageSize, null);
        }
        
        public void GetPagedAlbumsAsync(int pageIndex, int pageSize, object userState) {
            if ((this.onBeginGetPagedAlbumsDelegate == null)) {
                this.onBeginGetPagedAlbumsDelegate = new BeginOperationDelegate(this.OnBeginGetPagedAlbums);
            }
            if ((this.onEndGetPagedAlbumsDelegate == null)) {
                this.onEndGetPagedAlbumsDelegate = new EndOperationDelegate(this.OnEndGetPagedAlbums);
            }
            if ((this.onGetPagedAlbumsCompletedDelegate == null)) {
                this.onGetPagedAlbumsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPagedAlbumsCompleted);
            }
            base.InvokeAsync(this.onBeginGetPagedAlbumsDelegate, new object[] {
                        pageIndex,
                        pageSize}, this.onEndGetPagedAlbumsDelegate, this.onGetPagedAlbumsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginSaveAlbum(LiteApp.MySpace.Services.Photo.Album album, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveAlbum(album, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void LiteApp.MySpace.Services.Photo.PhotoService.EndSaveAlbum(System.IAsyncResult result) {
            base.Channel.EndSaveAlbum(result);
        }
        
        private System.IAsyncResult OnBeginSaveAlbum(object[] inValues, System.AsyncCallback callback, object asyncState) {
            LiteApp.MySpace.Services.Photo.Album album = ((LiteApp.MySpace.Services.Photo.Album)(inValues[0]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginSaveAlbum(album, callback, asyncState);
        }
        
        private object[] OnEndSaveAlbum(System.IAsyncResult result) {
            ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndSaveAlbum(result);
            return null;
        }
        
        private void OnSaveAlbumCompleted(object state) {
            if ((this.SaveAlbumCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveAlbumCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveAlbumAsync(LiteApp.MySpace.Services.Photo.Album album) {
            this.SaveAlbumAsync(album, null);
        }
        
        public void SaveAlbumAsync(LiteApp.MySpace.Services.Photo.Album album, object userState) {
            if ((this.onBeginSaveAlbumDelegate == null)) {
                this.onBeginSaveAlbumDelegate = new BeginOperationDelegate(this.OnBeginSaveAlbum);
            }
            if ((this.onEndSaveAlbumDelegate == null)) {
                this.onEndSaveAlbumDelegate = new EndOperationDelegate(this.OnEndSaveAlbum);
            }
            if ((this.onSaveAlbumCompletedDelegate == null)) {
                this.onSaveAlbumCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveAlbumCompleted);
            }
            base.InvokeAsync(this.onBeginSaveAlbumDelegate, new object[] {
                        album}, this.onEndSaveAlbumDelegate, this.onSaveAlbumCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginDeleteAlbum(string albumId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteAlbum(albumId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void LiteApp.MySpace.Services.Photo.PhotoService.EndDeleteAlbum(System.IAsyncResult result) {
            base.Channel.EndDeleteAlbum(result);
        }
        
        private System.IAsyncResult OnBeginDeleteAlbum(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string albumId = ((string)(inValues[0]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginDeleteAlbum(albumId, callback, asyncState);
        }
        
        private object[] OnEndDeleteAlbum(System.IAsyncResult result) {
            ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndDeleteAlbum(result);
            return null;
        }
        
        private void OnDeleteAlbumCompleted(object state) {
            if ((this.DeleteAlbumCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteAlbumCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAlbumAsync(string albumId) {
            this.DeleteAlbumAsync(albumId, null);
        }
        
        public void DeleteAlbumAsync(string albumId, object userState) {
            if ((this.onBeginDeleteAlbumDelegate == null)) {
                this.onBeginDeleteAlbumDelegate = new BeginOperationDelegate(this.OnBeginDeleteAlbum);
            }
            if ((this.onEndDeleteAlbumDelegate == null)) {
                this.onEndDeleteAlbumDelegate = new EndOperationDelegate(this.OnEndDeleteAlbum);
            }
            if ((this.onDeleteAlbumCompletedDelegate == null)) {
                this.onDeleteAlbumCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteAlbumCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteAlbumDelegate, new object[] {
                        albumId}, this.onEndDeleteAlbumDelegate, this.onDeleteAlbumCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginGetPagedPhotos(int pageIndex, int pageSize, string albumId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPagedPhotos(pageIndex, pageSize, albumId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiteApp.MySpace.Services.Photo.PagedResultOfPhotoYX32z0hB LiteApp.MySpace.Services.Photo.PhotoService.EndGetPagedPhotos(System.IAsyncResult result) {
            return base.Channel.EndGetPagedPhotos(result);
        }
        
        private System.IAsyncResult OnBeginGetPagedPhotos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pageIndex = ((int)(inValues[0]));
            int pageSize = ((int)(inValues[1]));
            string albumId = ((string)(inValues[2]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginGetPagedPhotos(pageIndex, pageSize, albumId, callback, asyncState);
        }
        
        private object[] OnEndGetPagedPhotos(System.IAsyncResult result) {
            LiteApp.MySpace.Services.Photo.PagedResultOfPhotoYX32z0hB retVal = ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndGetPagedPhotos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPagedPhotosCompleted(object state) {
            if ((this.GetPagedPhotosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPagedPhotosCompleted(this, new GetPagedPhotosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPagedPhotosAsync(int pageIndex, int pageSize, string albumId) {
            this.GetPagedPhotosAsync(pageIndex, pageSize, albumId, null);
        }
        
        public void GetPagedPhotosAsync(int pageIndex, int pageSize, string albumId, object userState) {
            if ((this.onBeginGetPagedPhotosDelegate == null)) {
                this.onBeginGetPagedPhotosDelegate = new BeginOperationDelegate(this.OnBeginGetPagedPhotos);
            }
            if ((this.onEndGetPagedPhotosDelegate == null)) {
                this.onEndGetPagedPhotosDelegate = new EndOperationDelegate(this.OnEndGetPagedPhotos);
            }
            if ((this.onGetPagedPhotosCompletedDelegate == null)) {
                this.onGetPagedPhotosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPagedPhotosCompleted);
            }
            base.InvokeAsync(this.onBeginGetPagedPhotosDelegate, new object[] {
                        pageIndex,
                        pageSize,
                        albumId}, this.onEndGetPagedPhotosDelegate, this.onGetPagedPhotosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginDeletePhotos(System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.DeletePhotoParameters> photos, string albumId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeletePhotos(photos, albumId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> LiteApp.MySpace.Services.Photo.PhotoService.EndDeletePhotos(System.IAsyncResult result) {
            return base.Channel.EndDeletePhotos(result);
        }
        
        private System.IAsyncResult OnBeginDeletePhotos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.DeletePhotoParameters> photos = ((System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.DeletePhotoParameters>)(inValues[0]));
            string albumId = ((string)(inValues[1]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginDeletePhotos(photos, albumId, callback, asyncState);
        }
        
        private object[] OnEndDeletePhotos(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndDeletePhotos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeletePhotosCompleted(object state) {
            if ((this.DeletePhotosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeletePhotosCompleted(this, new DeletePhotosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeletePhotosAsync(System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.DeletePhotoParameters> photos, string albumId) {
            this.DeletePhotosAsync(photos, albumId, null);
        }
        
        public void DeletePhotosAsync(System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.DeletePhotoParameters> photos, string albumId, object userState) {
            if ((this.onBeginDeletePhotosDelegate == null)) {
                this.onBeginDeletePhotosDelegate = new BeginOperationDelegate(this.OnBeginDeletePhotos);
            }
            if ((this.onEndDeletePhotosDelegate == null)) {
                this.onEndDeletePhotosDelegate = new EndOperationDelegate(this.OnEndDeletePhotos);
            }
            if ((this.onDeletePhotosCompletedDelegate == null)) {
                this.onDeletePhotosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeletePhotosCompleted);
            }
            base.InvokeAsync(this.onBeginDeletePhotosDelegate, new object[] {
                        photos,
                        albumId}, this.onEndDeletePhotosDelegate, this.onDeletePhotosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginUpdateDescription(string description, string photoId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateDescription(description, photoId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void LiteApp.MySpace.Services.Photo.PhotoService.EndUpdateDescription(System.IAsyncResult result) {
            base.Channel.EndUpdateDescription(result);
        }
        
        private System.IAsyncResult OnBeginUpdateDescription(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string description = ((string)(inValues[0]));
            string photoId = ((string)(inValues[1]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginUpdateDescription(description, photoId, callback, asyncState);
        }
        
        private object[] OnEndUpdateDescription(System.IAsyncResult result) {
            ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndUpdateDescription(result);
            return null;
        }
        
        private void OnUpdateDescriptionCompleted(object state) {
            if ((this.UpdateDescriptionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateDescriptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateDescriptionAsync(string description, string photoId) {
            this.UpdateDescriptionAsync(description, photoId, null);
        }
        
        public void UpdateDescriptionAsync(string description, string photoId, object userState) {
            if ((this.onBeginUpdateDescriptionDelegate == null)) {
                this.onBeginUpdateDescriptionDelegate = new BeginOperationDelegate(this.OnBeginUpdateDescription);
            }
            if ((this.onEndUpdateDescriptionDelegate == null)) {
                this.onEndUpdateDescriptionDelegate = new EndOperationDelegate(this.OnEndUpdateDescription);
            }
            if ((this.onUpdateDescriptionCompletedDelegate == null)) {
                this.onUpdateDescriptionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateDescriptionCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDescriptionDelegate, new object[] {
                        description,
                        photoId}, this.onEndUpdateDescriptionDelegate, this.onUpdateDescriptionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginGetComments(string photoId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetComments(photoId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.PhotoComment> LiteApp.MySpace.Services.Photo.PhotoService.EndGetComments(System.IAsyncResult result) {
            return base.Channel.EndGetComments(result);
        }
        
        private System.IAsyncResult OnBeginGetComments(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string photoId = ((string)(inValues[0]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginGetComments(photoId, callback, asyncState);
        }
        
        private object[] OnEndGetComments(System.IAsyncResult result) {
            System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.PhotoComment> retVal = ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndGetComments(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCommentsCompleted(object state) {
            if ((this.GetCommentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCommentsCompleted(this, new GetCommentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCommentsAsync(string photoId) {
            this.GetCommentsAsync(photoId, null);
        }
        
        public void GetCommentsAsync(string photoId, object userState) {
            if ((this.onBeginGetCommentsDelegate == null)) {
                this.onBeginGetCommentsDelegate = new BeginOperationDelegate(this.OnBeginGetComments);
            }
            if ((this.onEndGetCommentsDelegate == null)) {
                this.onEndGetCommentsDelegate = new EndOperationDelegate(this.OnEndGetComments);
            }
            if ((this.onGetCommentsCompletedDelegate == null)) {
                this.onGetCommentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCommentsCompleted);
            }
            base.InvokeAsync(this.onBeginGetCommentsDelegate, new object[] {
                        photoId}, this.onEndGetCommentsDelegate, this.onGetCommentsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginSaveComment(LiteApp.MySpace.Services.Photo.PhotoComment comment, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveComment(comment, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiteApp.MySpace.Services.Photo.PhotoComment LiteApp.MySpace.Services.Photo.PhotoService.EndSaveComment(System.IAsyncResult result) {
            return base.Channel.EndSaveComment(result);
        }
        
        private System.IAsyncResult OnBeginSaveComment(object[] inValues, System.AsyncCallback callback, object asyncState) {
            LiteApp.MySpace.Services.Photo.PhotoComment comment = ((LiteApp.MySpace.Services.Photo.PhotoComment)(inValues[0]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginSaveComment(comment, callback, asyncState);
        }
        
        private object[] OnEndSaveComment(System.IAsyncResult result) {
            LiteApp.MySpace.Services.Photo.PhotoComment retVal = ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndSaveComment(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveCommentCompleted(object state) {
            if ((this.SaveCommentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveCommentCompleted(this, new SaveCommentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveCommentAsync(LiteApp.MySpace.Services.Photo.PhotoComment comment) {
            this.SaveCommentAsync(comment, null);
        }
        
        public void SaveCommentAsync(LiteApp.MySpace.Services.Photo.PhotoComment comment, object userState) {
            if ((this.onBeginSaveCommentDelegate == null)) {
                this.onBeginSaveCommentDelegate = new BeginOperationDelegate(this.OnBeginSaveComment);
            }
            if ((this.onEndSaveCommentDelegate == null)) {
                this.onEndSaveCommentDelegate = new EndOperationDelegate(this.OnEndSaveComment);
            }
            if ((this.onSaveCommentCompletedDelegate == null)) {
                this.onSaveCommentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCommentCompleted);
            }
            base.InvokeAsync(this.onBeginSaveCommentDelegate, new object[] {
                        comment}, this.onEndSaveCommentDelegate, this.onSaveCommentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LiteApp.MySpace.Services.Photo.PhotoService.BeginDeleteComment(string commentId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteComment(commentId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void LiteApp.MySpace.Services.Photo.PhotoService.EndDeleteComment(System.IAsyncResult result) {
            base.Channel.EndDeleteComment(result);
        }
        
        private System.IAsyncResult OnBeginDeleteComment(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string commentId = ((string)(inValues[0]));
            return ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).BeginDeleteComment(commentId, callback, asyncState);
        }
        
        private object[] OnEndDeleteComment(System.IAsyncResult result) {
            ((LiteApp.MySpace.Services.Photo.PhotoService)(this)).EndDeleteComment(result);
            return null;
        }
        
        private void OnDeleteCommentCompleted(object state) {
            if ((this.DeleteCommentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCommentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteCommentAsync(string commentId) {
            this.DeleteCommentAsync(commentId, null);
        }
        
        public void DeleteCommentAsync(string commentId, object userState) {
            if ((this.onBeginDeleteCommentDelegate == null)) {
                this.onBeginDeleteCommentDelegate = new BeginOperationDelegate(this.OnBeginDeleteComment);
            }
            if ((this.onEndDeleteCommentDelegate == null)) {
                this.onEndDeleteCommentDelegate = new EndOperationDelegate(this.OnEndDeleteComment);
            }
            if ((this.onDeleteCommentCompletedDelegate == null)) {
                this.onDeleteCommentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCommentCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteCommentDelegate, new object[] {
                        commentId}, this.onEndDeleteCommentDelegate, this.onDeleteCommentCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LiteApp.MySpace.Services.Photo.PhotoService CreateChannel() {
            return new PhotoServiceClientChannel(this);
        }
        
        private class PhotoServiceClientChannel : ChannelBase<LiteApp.MySpace.Services.Photo.PhotoService>, LiteApp.MySpace.Services.Photo.PhotoService {
            
            public PhotoServiceClientChannel(System.ServiceModel.ClientBase<LiteApp.MySpace.Services.Photo.PhotoService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPagedAlbums(int pageIndex, int pageSize, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = pageIndex;
                _args[1] = pageSize;
                System.IAsyncResult _result = base.BeginInvoke("GetPagedAlbums", _args, callback, asyncState);
                return _result;
            }
            
            public LiteApp.MySpace.Services.Photo.PagedResultOfAlbumYX32z0hB EndGetPagedAlbums(System.IAsyncResult result) {
                object[] _args = new object[0];
                LiteApp.MySpace.Services.Photo.PagedResultOfAlbumYX32z0hB _result = ((LiteApp.MySpace.Services.Photo.PagedResultOfAlbumYX32z0hB)(base.EndInvoke("GetPagedAlbums", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveAlbum(LiteApp.MySpace.Services.Photo.Album album, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = album;
                System.IAsyncResult _result = base.BeginInvoke("SaveAlbum", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveAlbum(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveAlbum", _args, result);
            }
            
            public System.IAsyncResult BeginDeleteAlbum(string albumId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = albumId;
                System.IAsyncResult _result = base.BeginInvoke("DeleteAlbum", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteAlbum(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteAlbum", _args, result);
            }
            
            public System.IAsyncResult BeginGetPagedPhotos(int pageIndex, int pageSize, string albumId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = pageIndex;
                _args[1] = pageSize;
                _args[2] = albumId;
                System.IAsyncResult _result = base.BeginInvoke("GetPagedPhotos", _args, callback, asyncState);
                return _result;
            }
            
            public LiteApp.MySpace.Services.Photo.PagedResultOfPhotoYX32z0hB EndGetPagedPhotos(System.IAsyncResult result) {
                object[] _args = new object[0];
                LiteApp.MySpace.Services.Photo.PagedResultOfPhotoYX32z0hB _result = ((LiteApp.MySpace.Services.Photo.PagedResultOfPhotoYX32z0hB)(base.EndInvoke("GetPagedPhotos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeletePhotos(System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.DeletePhotoParameters> photos, string albumId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = photos;
                _args[1] = albumId;
                System.IAsyncResult _result = base.BeginInvoke("DeletePhotos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndDeletePhotos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("DeletePhotos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateDescription(string description, string photoId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = description;
                _args[1] = photoId;
                System.IAsyncResult _result = base.BeginInvoke("UpdateDescription", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateDescription(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateDescription", _args, result);
            }
            
            public System.IAsyncResult BeginGetComments(string photoId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = photoId;
                System.IAsyncResult _result = base.BeginInvoke("GetComments", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.PhotoComment> EndGetComments(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.PhotoComment> _result = ((System.Collections.Generic.List<LiteApp.MySpace.Services.Photo.PhotoComment>)(base.EndInvoke("GetComments", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveComment(LiteApp.MySpace.Services.Photo.PhotoComment comment, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = comment;
                System.IAsyncResult _result = base.BeginInvoke("SaveComment", _args, callback, asyncState);
                return _result;
            }
            
            public LiteApp.MySpace.Services.Photo.PhotoComment EndSaveComment(System.IAsyncResult result) {
                object[] _args = new object[0];
                LiteApp.MySpace.Services.Photo.PhotoComment _result = ((LiteApp.MySpace.Services.Photo.PhotoComment)(base.EndInvoke("SaveComment", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteComment(string commentId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = commentId;
                System.IAsyncResult _result = base.BeginInvoke("DeleteComment", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteComment(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteComment", _args, result);
            }
        }
    }
}
